articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("articles/", views.ArticleListView.as_view(), name="list"),
    path("articles/<int:article_id>", views.ArticleDetailView.as_view(), name="detail"),
    path("bureaus/<slug:slug>", views.BureauDetailView.as_view(), name="bureau"),
]

hosnakpub/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(os.environ.get("ADMIN_URL"), admin.site.urls),
    path("", include("articles.urls")),
    path("markdownx/", include("markdownx.urls")),
]

if os.environ.get("DEBUG") == "True":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class HPServiceUser(AbstractUser):
    pass

articles/models.py
import bleach
from bleach_allowlist import markdown_attrs, markdown_tags
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from contents.utils import markdown_to_content


# Create your models here.
class Bureau(models.Model):
    name = models.CharField(verbose_name="局名", max_length=10)
    slug = models.SlugField(verbose_name="slug")
    content_with_markdown = MarkdownxField(verbose_name="局紹介文のマークダウン記述")
    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="最終更新日時", auto_now=True)

    def get_content(self):
        return markdown_to_content(self.content_with_markdown)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "局"
        verbose_name_plural = "局"


class Article(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=255)
    content_with_markdown = MarkdownxField(verbose_name="内容のマークダウン記述")
    is_published = models.BooleanField(verbose_name="公開", default=False)
    bureau = models.ForeignKey(
        Bureau, on_delete=models.SET_NULL, verbose_name="記事局", blank=True, null=True
    )
    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="最終更新日時", auto_now=True)

    def get_content(self):
        return markdown_to_content(self.content_with_markdown)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "記事"
        verbose_name_plural = "記事"

articles/views.py
from typing import Any, Dict

from django.db import models
from django.views import generic

from .models import Article, Bureau


# Create your views here.
class IndexView(generic.TemplateView):
    template_name = "articles/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["new_articles"] = Article.objects.filter(is_published=True).order_by(
            "-updated_at"
        )[:5]
        context["bureaus"] = Bureau.objects.all()
        return context


class ArticleListView(generic.ListView):
    queryset = Article.objects.filter(is_published=True).order_by("-updated_at")
    template_name = "articles/list.html"
    context_object_name = "articles"


class ArticleDetailView(generic.DetailView):
    template_name = "articles/detail.html"
    pk_url_kwarg = "article_id"
    context_object_name = "article"

    def get_queryset(self):
        if self.request.user.is_staff:
            return Article.objects.all()
        return Article.objects.filter(is_published=True)


class BureauDetailView(generic.DetailView):
    template_name = "articles/bureau.html"
    context_object_name = "bureau"
    model = Bureau

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context["articles"] = Article.objects.filter(
            bureau=context["bureau"], is_published=True
        )
        return context

contents/templates/articles/bureau.html
{% extends "base.html" %}
{% load sass_tags %}
{% load static %}

{% block title %}{{ bureau.name }} | {% endblock %}

{% block additional_style %}
  <!-- CSSを記事詳細と共有 -->
  <link rel="stylesheet" href="{% sass_src 'css/articles/detail.scss' %}">
{% endblock %}

{% block heading %}
  <h1><div id="name">{{ bureau.name }}</div></h1>
  <div id="updated_at">更新日時: {{ bureau.updated_at | date:"Y/m/d H:i" }}</div>
{% endblock %}

{% block main %}
  <div id="content">{{ bureau.get_content | safe }}</div>
  <div id="articles"><span class="title"><h2>局記事一覧</h2></span>
    <ul>
      {% for article in articles %}
      <li><a href="{% url 'articles:detail' article.id %}">{{ article.title }}</a></li>
      {% endfor %}
    </ul>
  </div>
  <div id="committees"><span class="title"><h2>委員会一覧</h2></span></div>
{% endblock %}

contents/templates/articles/detail.html
{% extends "base.html" %}
{% load sass_tags %}
{% load static %}

{% block title %}{% if not article.is_published %}（下書き）{% endif %}{{ article.title }} | {% endblock %}

{% block additional_style %}
  <link rel="stylesheet" href="{% sass_src 'css/articles/detail.scss' %}">
{% endblock %}

{% block heading %}
  {% if not article.is_published %}<div id="draft">（下書き）</div>{% endif %}
  <h1><div id="title">{{ article.title }}</div></h1>
  <div id="updated_at">更新日時: {{ article.updated_at | date:"Y/m/d H:i" }}</div>
  <div id="bureau">
    {% if article.bureau %}
      局: <a href="{% url 'articles:bureau' article.bureau.slug %}">{{ article.bureau.name }}</a>
    {% endif %}
  </div>
{% endblock %}

{% block main %}
  <div id="content">{{ article.get_content | safe }}</div>
  <div id="list"><a href="{% url 'articles:list' %}">記事一覧へ</a></div>
{% endblock %}

contents/templates/articles/index.html
{% extends "base.html" %}
{% load sass_tags %}
{% load static %}
{% block additional_style %}
<meta name="description" content="個人ブログ・ほしのなか政府のWebサイトへようこそ。">
{% endblock %}
{% block heading %}
  <h1>ほしのなか政府 トップページ</h1>
  <p class="text">ほしのなか政府のWebサイトへようこそ</p>
{% endblock %}
{% block main %}
  <h2 class="title">最新記事</h2>
  <p>
    <ul>
      {% for article in new_articles %}
      <li><a href="{% url 'articles:detail' article.id %}">{{ article.title }}</a></li>
      {% endfor %}
    </ul>
  </p>
  <p class="right"><a href="{% url 'articles:list' %}">記事一覧へ</a></p>
  <h2 class="title">局一覧</h2>
    <ul>
      {% for bureau in bureaus %}
      <li><a href="{% url 'articles:bureau' bureau.slug %}">{{ bureau.name }}</a></li>
      {% endfor %}
    </ul>
  <h2 class="title">ほしのなか政府について</h2>
  <p class="text">ほしのなか政府については、<a href="{% url 'articles:detail' 1 %}">こちらの記事</a>をご覧ください。</p>
  <h2 class="title">全民議会構成</h2>
  <div class="infogram-embed" data-id="c1721866-5bee-4218-93cd-35496abbf5bc" data-type="interactive" data-title="全民議会" style="height: auto;max-width: 500px;margin: 0 auto;"></div>
    <script>!function(e,i,n,s){var t="InfogramEmbeds",d=e.getElementsByTagName("script")[0];if(window[t]&&window[t].initialized)window[t].process&&window[t].process();else if(!e.getElementById(n)){var o=e.createElement("script");o.async=1,o.id=n,o.src="https://e.infogram.com/js/dist/embed-loader-min.js",d.parentNode.insertBefore(o,d)}}(document,0,"infogram-async");</script>
{% endblock %}

contents/templates/articles/list.html
{% extends "base.html" %}
{% load sass_tags %}
{% load static %}
{% block title %}記事一覧 | {% endblock %}
{% block heading %}
  <h1>記事一覧</h1>
  <p class="text">記事の一覧です。</p>
{% endblock %}
{% block main %}  
  <ul>
    {% for article in articles %}
    <li><a href="{% url 'articles:detail' article.id %}">{{ article.title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

contents/templates/base.html
<!DOCTYPE html>
{% load sass_tags %}
{% load static %}
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}ほしのなか政府</title>
  <link rel="stylesheet" href="{% sass_src 'css/base.scss' %}">
  {% block additional_style %}{% endblock %}
  <link rel="icon" href="{% static 'image/favicon.ico' %}" type="image/x-icon">
</head>
<body>
  <header>
    <nav>
      
      <ul class="headerNavigation">
        <li><a href="{% url 'articles:index' %}"><img src="{% static 'image/logo.png' %}" height="75px"></a></li>
        <li><a class="navItem" href="{% url 'articles:list' %}">記事一覧</a></li>
      </ul>
    </nav>
  </header>
  <div class="heading">
    {% block heading %}{% endblock %}
  </div>
  <div class="main">
    {% block main %}{% endblock %}
  </div>
  <footer>
    <img src="{% static 'image/logo.png' %}" height="30px" style="padding-right: 5px;">
    <p>©️ 2023 Hoshinonaka/Snak</p>
  </footer>
</body>
</html>